// WebP + JPG/PNG fallback for images rendered from data (museums/routes/events/
// news/places). Every raster file in assets/img has a .webp sibling generated by
// scripts/build-images.mjs; index.html uses the same <picture> pattern statically.
//
// Only local assets/img/*.jpg|png paths are wrapped — either site-relative
// ("assets/img/…") or already resolved with siteUrl() ("<BASE_URL>assets/img/…",
// js/base-url.js). Absolute URLs coming from the API (or anything else) are
// returned as the plain <img> unchanged.
import { BASE_URL } from "./base-url.js";

const escapeRe = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const LOCAL_RASTER = new RegExp(`^(?:${escapeRe(BASE_URL)})?assets/img/[^"?#]+\\.(jpe?g|png)$`, "i");

export function picture(src, imgHtml) {
  if (!LOCAL_RASTER.test(src || "")) return imgHtml;
  const webp = String(src).replace(/\.(jpe?g|png)$/i, ".webp").replace(/"/g, "&quot;");
  return `<picture><source srcset="${webp}" type="image/webp">${imgHtml}</picture>`;
}

// If a .webp sibling is missing (e.g. a new JPG was added without re-running the
// build script), the browser does NOT fall back to <img src> by itself — it just
// fires "error". Drop the <source> and retry with the original file; the event is
// swallowed so per-module error handlers (js/places.js wirePhotoFallback) only
// react when the JPG/PNG itself is missing too.
window.addEventListener("error", (e) => {
  const img = e.target;
  if (!(img instanceof HTMLImageElement)) return;
  const source = img.parentElement?.tagName === "PICTURE"
    && img.parentElement.querySelector('source[type="image/webp"]');
  if (!source) return;
  e.stopImmediatePropagation();
  source.remove();
  img.src = img.getAttribute("src");
}, true);
